# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a515f1635cd49000d58a7da772e1924597ea5bff726314f062871227e428f97611132ca141a1813c15521ba787516c4d5bc433f026a40e24d1b28e007ed9f9a0

test:
  secret_key_base: 45b51bd6ffd39a04587f6b8a71f0c7d700adefd46f955608aa1becb4f9b9c0a225dc8ae1cbe8b97140351865288c879a7ac3dcf9bb4ab6507f37ee2e080800b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
